/**
 * Stamp a draft article as accepted by:
 * 1. Getting the current article file from the repo
 * 2. Creating a new branch
 * 3. Committing the status change (draft → accepted)
 * 4. Opening a PR for manual merge
 *
 * All GitHub API calls go through /api/github/[...path] proxy.
 * The token is never in the browser — it lives in an httpOnly cookie.
 */

const REPO = 'repos/ojfbot/daily-logger'

interface StampResult {
  prNumber: number
  prUrl: string
}

async function ghFetch(path: string, options?: RequestInit): Promise<Response> {
  const url = `/api/github/${path}`
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
    ...(options?.headers as Record<string, string> ?? {}),
  }

  // Add CSRF header for mutating requests
  const method = (options?.method ?? 'GET').toUpperCase()
  if (method !== 'GET' && method !== 'HEAD') {
    headers['X-Requested-With'] = 'XMLHttpRequest'
  }

  return fetch(url, {
    ...options,
    headers,
    credentials: 'same-origin',
  })
}

export async function stampDraft(date: string, articleTitle: string, userLogin: string, editorialFeedback?: string): Promise<StampResult> {
  const branch = `accept/${date}`
  const filePath = `_articles/${date}.md`

  // ── 1. Check if a PR/branch already exists ─────────────────────────────
  const existingBranch = await ghFetch(`${REPO}/git/refs/heads/${branch}`)
  if (existingBranch.ok) {
    // Branch exists — check for open PR
    const prsRes = await ghFetch(`${REPO}/pulls?head=ojfbot:${branch}&state=open`)
    if (prsRes.ok) {
      const prs = await prsRes.json() as Array<{ number: number; html_url: string }>
      if (prs.length > 0) {
        throw new Error(`Already stamped — PR #${prs[0].number} is open`)
      }
    }
    throw new Error(`Branch ${branch} already exists`)
  }

  // ── 2. Get current article content from main ───────────────────────────
  const fileRes = await ghFetch(`${REPO}/contents/${filePath}?ref=main`)
  if (!fileRes.ok) {
    throw new Error(`Could not read article: ${fileRes.status}`)
  }

  const fileData = await fileRes.json() as { content: string; sha: string; encoding: string }
  const content = atob(fileData.content.replace(/\n/g, ''))

  // ── 3. Update status in frontmatter ────────────────────────────────────
  const updated = content.replace(
    /^status:\s*"?draft"?\s*$/m,
    'status: "accepted"',
  )

  if (updated === content) {
    throw new Error('Article is not in draft status')
  }

  // ── 4. Get main branch SHA for branch creation ─────────────────────────
  const mainRefRes = await ghFetch(`${REPO}/git/refs/heads/main`)
  if (!mainRefRes.ok) {
    throw new Error(`Could not get main branch ref: ${mainRefRes.status}`)
  }
  const mainRef = await mainRefRes.json() as { object: { sha: string } }

  // ── 5. Create the accept branch ────────────────────────────────────────
  const createBranchRes = await ghFetch(`${REPO}/git/refs`, {
    method: 'POST',
    body: JSON.stringify({
      ref: `refs/heads/${branch}`,
      sha: mainRef.object.sha,
    }),
  })

  if (!createBranchRes.ok) {
    const err = await createBranchRes.json() as { message?: string }
    throw new Error(`Could not create branch: ${err.message ?? createBranchRes.status}`)
  }

  // ── 6. Commit the status change ────────────────────────────────────────
  const commitRes = await ghFetch(`${REPO}/contents/${filePath}`, {
    method: 'PUT',
    body: JSON.stringify({
      message: `editorial: accept ${date} draft`,
      content: btoa(updated),
      sha: fileData.sha,
      branch,
    }),
  })

  if (!commitRes.ok) {
    const err = await commitRes.json() as { message?: string }
    throw new Error(`Could not commit: ${err.message ?? commitRes.status}`)
  }

  // ── 7. Open PR ─────────────────────────────────────────────────────────
  const now = new Date().toISOString()
  const hasRevisions = !!editorialFeedback
  const prBody = [
    `## Editorial: ${hasRevisions ? 'Accept with revisions' : 'Accept'} ${date} Draft`,
    '',
    `**Article:** ${articleTitle}`,
    `**Stamped by:** @${userLogin}`,
    `**Date accepted:** ${now}`,
    '',
    '### Changes',
    '- Updated article status from `draft` to `accepted`',
    ...(hasRevisions
      ? [
          '- **Editorial feedback attached** — CI will apply revisions via LLM',
          '',
          '### Editorial Feedback',
          '',
          '<!-- EDITORIAL_FEEDBACK_START -->',
          editorialFeedback!,
          '<!-- EDITORIAL_FEEDBACK_END -->',
        ]
      : []),
    '',
    '### Review',
    'This PR was created by the daily-logger editorial UI.',
    hasRevisions
      ? 'CI will process the editorial feedback and push revised content to this branch.'
      : 'Manual merge required.',
    '',
    '---',
    'Generated by daily-logger editorial stamper',
  ].join('\n')

  const prRes = await ghFetch(`${REPO}/pulls`, {
    method: 'POST',
    body: JSON.stringify({
      title: `editorial: accept ${date} draft`,
      body: prBody,
      head: branch,
      base: 'main',
    }),
  })

  if (!prRes.ok) {
    const err = await prRes.json() as { message?: string }
    throw new Error(`Could not create PR: ${err.message ?? prRes.status}`)
  }

  const pr = await prRes.json() as { number: number; html_url: string }
  return { prNumber: pr.number, prUrl: pr.html_url }
}
