#!/usr/bin/env python3
"""
Build the draft PR body for a daily article.
Usage: python3 build_pr_body.py <date> <branch> <article_path>
Writes markdown to stdout — redirect to a file for gh pr create --body-file.
"""
import sys
import re
import json


def fm_field(fm: str, *patterns: str, default: str = "") -> str:
    for pat in patterns:
        m = re.search(pat, fm, re.MULTILINE)
        if m:
            return m.group(1).strip()
    return default


def main() -> None:
    date, branch, article_path = sys.argv[1], sys.argv[2], sys.argv[3]
    text = open(article_path).read()

    # --- frontmatter ---
    fm_match = re.match(r"^---\n(.+?)\n---\n", text, re.DOTALL)
    fm = fm_match.group(1) if fm_match else ""

    title = fm_field(fm,
        r'^title:\s+"(.+)"',
        r"^title:\s+'(.+)'",
        r"^title:\s+(.+)",
        default="(untitled)",
    )
    tags_raw = fm_field(fm, r"^tags:\s+(.+)", default="")
    try:
        tags = ", ".join(f"`{t}`" for t in json.loads(tags_raw))
    except (json.JSONDecodeError, TypeError):
        tags = tags_raw
    summary = fm_field(fm,
        r'^summary:\s+"(.+)"',
        r"^summary:\s+'(.+)'",
        r"^summary:\s+(.+)",
        default="",
    )

    # --- body preview ---
    # Grab content between the closing frontmatter --- and the trailing --- footer.
    body_match = re.search(
        r"^---\n.+?^---\n(.+?)(?:^---\n|\Z)", text, re.DOTALL | re.MULTILINE
    )
    body = body_match.group(1).strip() if body_match else ""
    preview = body[:1800] + ("\n\n_\u2026article continues_" if len(body) > 1800 else "")

    repos = (
        "`shell`, `cv-builder`, `BlogEngine`, `TripPlanner`, "
        "`node-template`, `MrPlug`, `purefoy`, `daily-logger`"
    )

    print(
        f"## \U0001f4dd Daily article \u2014 {date}\n"
        "\n"
        f'**Title:** "{title}"  \n'
        f"**Tags:** {tags}  \n"
        f"**Summary:** {summary}\n"
        "\n"
        "---\n"
        "\n"
        "### Preview\n"
        "\n"
        f"{preview}\n"
        "\n"
        "---\n"
        "\n"
        "### Source sweep\n"
        "\n"
        f"Repos: {repos}  \n"
        "Window: commits (last 24\u202fh) \u00b7 PRs & issues (last 7 days)\n"
        "\n"
        "---\n"
        "\n"
        "### Editorial actions\n"
        "\n"
        "| | How |\n"
        "|---|---|\n"
        "| \u2705 **Publish** | Merge this PR |\n"
        f"| \u270f\ufe0f **Edit** | Push changes to `{branch}`, then merge |\n"
        "| \u23ed\ufe0f **Skip** | Close this PR without merging |\n"
        "\n"
        "_Generated by [daily-logger](https://github.com/ojfbot/daily-logger)_\n"
    )


if __name__ == "__main__":
    main()
